"""Framework-neutral domain types.

This package is the stable centre of the system: messages, tools, events,
context, runs, policy decisions and errors, expressed with nothing but the
standard library and Pydantic. No LangChain, LlamaIndex, LangGraph, FastAPI or
database type appears here, and none may. Swapping a model provider, a vector
store or a checkpointer must leave these definitions untouched -- that is the
property the architecture tests protect.
"""

from agent_workbench.domain.artifacts import ArtifactKind, ArtifactRef
from agent_workbench.domain.context import (
    Citation,
    ContextChunk,
    ContextPacket,
    SourceLocator,
)
from agent_workbench.domain.errors import (
    AgentWorkbenchError,
    ApprovalRequiredError,
    BudgetExceededError,
    ErrorCode,
    ErrorInfo,
    IncompatibleSchemaError,
    OperationCancelledError,
    OutputTooLargeError,
    PolicyDeniedError,
    ProviderError,
    StaleExecutionError,
    ToolFailedError,
    ToolInputInvalidError,
    ToolPairingError,
    ToolTimeoutError,
    UnknownToolError,
)
from agent_workbench.domain.events import (
    DURABLE_EVENT_TYPES,
    EVENT_DURABILITY,
    TRANSIENT_EVENT_TYPES,
    AnswerCommitted,
    AnswerWithheld,
    ChatTurnExpired,
    Durability,
    EventEnvelope,
    EventPayload,
    EventType,
    TaskAwaitingApproval,
    TaskCancelled,
    TaskClaimed,
    TaskDeadLettered,
    TaskFailed,
    TaskParkedForMigration,
    TaskRetryScheduled,
    TaskSubmitted,
    TaskSucceeded,
)
from agent_workbench.domain.evidence import (
    EvidenceBundle,
    EvidenceItem,
    EvidenceRevision,
    ExternalSearchHit,
)
from agent_workbench.domain.identifiers import Identifier
from agent_workbench.domain.messages import (
    ContentBlock,
    Message,
    MessageRole,
    TextBlock,
    ToolResultBlock,
    ToolUseBlock,
    assistant_message,
    tool_message,
    user_message,
)
from agent_workbench.domain.policies import (
    AuthorizationEnvelope,
    ExecutionContext,
    PolicyDecision,
    PolicyEffect,
    PrincipalContext,
)
from agent_workbench.domain.runs import (
    AgentOutcome,
    AgentRunRequest,
    BudgetUsage,
    ModelProfileName,
    RunBudget,
    RunKind,
    RunState,
    RunStatus,
    StopReason,
    TokenUsage,
    TraceContext,
    stale_execution_outcome,
)
from agent_workbench.domain.schema import (
    DOMAIN_SCHEMA_VERSION,
    DomainModel,
    JsonObject,
    VersionedModel,
)
from agent_workbench.domain.task_inputs import TaskInput
from agent_workbench.domain.tasks import (
    CANONICAL_V1_NODE_IDS,
    CANONICAL_V2_NODE_IDS,
    ReviewDecision,
    ReviewResult,
    TaskNodeId,
    TaskState,
    TaskStep,
)
from agent_workbench.domain.tools import (
    ToolCall,
    ToolConcurrency,
    ToolIdempotency,
    ToolName,
    ToolResult,
    ToolResultStatus,
    ToolRisk,
    ToolSpec,
    align_results,
)

__all__ = [
    "CANONICAL_V1_NODE_IDS",
    "CANONICAL_V2_NODE_IDS",
    "DOMAIN_SCHEMA_VERSION",
    "DURABLE_EVENT_TYPES",
    "EVENT_DURABILITY",
    "TRANSIENT_EVENT_TYPES",
    "AgentOutcome",
    "AgentRunRequest",
    "AgentWorkbenchError",
    "AnswerCommitted",
    "AnswerWithheld",
    "ApprovalRequiredError",
    "ArtifactKind",
    "ArtifactRef",
    "AuthorizationEnvelope",
    "BudgetExceededError",
    "BudgetUsage",
    "ChatTurnExpired",
    "Citation",
    "ContentBlock",
    "ContextChunk",
    "ContextPacket",
    "DomainModel",
    "Durability",
    "ErrorCode",
    "ErrorInfo",
    "EventEnvelope",
    "EventPayload",
    "EventType",
    "EvidenceBundle",
    "EvidenceItem",
    "EvidenceRevision",
    "ExecutionContext",
    "ExternalSearchHit",
    "Identifier",
    "IncompatibleSchemaError",
    "JsonObject",
    "Message",
    "MessageRole",
    "ModelProfileName",
    "OperationCancelledError",
    "OutputTooLargeError",
    "PolicyDecision",
    "PolicyDeniedError",
    "PolicyEffect",
    "PrincipalContext",
    "ProviderError",
    "ReviewDecision",
    "ReviewResult",
    "RunBudget",
    "RunKind",
    "RunState",
    "RunStatus",
    "SourceLocator",
    "StaleExecutionError",
    "StopReason",
    "TaskAwaitingApproval",
    "TaskCancelled",
    "TaskClaimed",
    "TaskDeadLettered",
    "TaskFailed",
    "TaskInput",
    "TaskNodeId",
    "TaskParkedForMigration",
    "TaskRetryScheduled",
    "TaskState",
    "TaskStep",
    "TaskSubmitted",
    "TaskSucceeded",
    "TextBlock",
    "TokenUsage",
    "ToolCall",
    "ToolConcurrency",
    "ToolFailedError",
    "ToolIdempotency",
    "ToolInputInvalidError",
    "ToolName",
    "ToolPairingError",
    "ToolResult",
    "ToolResultBlock",
    "ToolResultStatus",
    "ToolRisk",
    "ToolSpec",
    "ToolTimeoutError",
    "ToolUseBlock",
    "TraceContext",
    "UnknownToolError",
    "VersionedModel",
    "align_results",
    "assistant_message",
    "stale_execution_outcome",
    "tool_message",
    "user_message",
]
