"""The shell commands that still stop at a person when a turn runs unattended.

ADR-0116. A turn that asks for ``approvals="unattended"`` has its destructive
calls -- every ``project_run``, every ``project_delete`` -- permitted by its
own rule instead of by a click, on the condition ADR-0115 made true: the
command runs in a container that mounts the project directory and holds
nothing else. That condition bounds the blast radius to one folder. It does
not bound it to nothing, and the folder is the user's work.

So a short list of shapes still asks, and the list is the whole of what
"unattended" does not cover. It is deliberately a list of *shapes* rather than
a classifier: Claude Code's auto mode puts a model in this seat and lets it
judge each command; this project has no second model to spend on the
question and would not trust the first one to grade its own homework. A
regular expression cannot judge intent, so each entry is chosen for the
thing it would cost if it ran unwatched, not for how dangerous it sounds --
``rm -rf build`` passes, because a build directory is regenerated by the
command that made it; ``rm -rf .`` asks, because the directory is the
project.

Domain rather than adapter, because two things outside any adapter read it:
the policy engine, which is the one place a call is judged, and the prompt,
which has to tell the model what will still stop. A list that lived beside the
tool would be a list the prompt could drift from.
"""

from __future__ import annotations

import re
from collections.abc import Mapping
from typing import Final

from pydantic import JsonValue

#: The argument a command travels in. ``project_run`` spells it this way and so
#: does the runner's own ``run_command``; a destructive tool that carries no
#: such key -- ``project_delete`` names a file, not a command -- has nothing
#: here to match and is permitted by the turn's rule like any other.
COMMAND_ARGUMENT: Final[str] = "command"

#: Targets of a recursive removal that mean "everything here" or "everything".
#: A path with a slash in the middle, or a bare directory name, is left alone:
#: ``rm -rf node_modules`` and ``rm -rf dist/assets`` are what a coding agent
#: does twenty times a day, and the container makes the worst case one folder.
_WHOLESALE_TARGETS: Final[str] = r"(?:\.|\./|\.\.|/|~|\*|\./\*|/\*|~/\*)"

#: Where a program name can stand: the start of the line, or after the
#: operators that start a new command -- `;`, `&&`, `||`, `|`, a subshell,
#: the quote that opens `sh -c "..."` -- with the wrappers that pass their
#: arguments through (`time`, `env`, `nohup`, an assignment) allowed in
#: between. A program named anywhere else is an argument: `grep -r sudo .`
#: searches for the word, `echo rm -rf .` prints it, `git commit -m 'sudo'`
#: records it, and none of them runs anything. The first draft anchored on
#: a word boundary and flagged the first; the second let any quote open a
#: command and flagged the third. Only `-c` followed by a quote is a shell
#: being handed a command.
_START: Final[str] = (
    r"(?:^|[;&|(`\n]|\$\(|-c\s+[\"'])\s*(?:(?:time|exec|nohup|env|nice)\s+)*"
    r"(?:\w+=\S*\s+)*"
)

#: What may follow the last token of a shape: whitespace, the end, or the
#: characters that close a command -- so `sh -c "rm -rf ."` matches with the
#: quote against the dot, and `rm -rf .git` does not match at all.
_END: Final[str] = r"(?=[\s\"';&|)]|$)"

#: Each entry is the reason it asks, then the pattern. The reason is what the
#: approval card and the log say, so it is written for the person reading it
#: and not for the person maintaining the list.
STILL_ASKS: Final[tuple[tuple[str, re.Pattern[str]], ...]] = (
    (
        # The project itself, or a whole tree from the root down. Uncommitted
        # work has no other copy.
        "removes the whole directory",
        re.compile(
            _START + r"rm\s+(?:-[a-zA-Z]*\s+)*-[a-zA-Z]*[rR][a-zA-Z]*\s+"
            r"(?:-[a-zA-Z]*\s+)*(?:--\s+)?" + _WHOLESALE_TARGETS + _END
        ),
    ),
    (
        # The same effect through git: `reset --hard`, `clean -f`, `checkout
        # -- .`, `restore .` each discard uncommitted changes with no undo.
        "discards uncommitted work",
        re.compile(
            _START + r"git\s+(?:reset\s+(?:\S+\s+)*--hard"
            r"|clean\s+(?:\S+\s+)*-[a-zA-Z]*[fF]"
            r"|checkout\s+(?:\S+\s+)*--\s+\."
            r"|checkout\s+\." + _END + r"|restore\s+(?:\S+\s+)*\." + _END + r")"
        ),
    ),
    (
        # History on somebody else's copy. The container holds no credentials
        # today, and the shape is listed anyway: a credential added later
        # must not silently arrive with a force-push already permitted.
        "rewrites shared history",
        re.compile(
            _START + r"git\s+push\s+(?:\S+\s+)*(?:--force(?:-with-lease)?|-f)" + _END
        ),
    ),
    (
        # Code fetched from the network and run before anyone read it.
        "runs code straight from the network",
        re.compile(
            _START
            + r"(?:curl|wget)\b[^|;&]*\|\s*(?:sudo\s+)?(?:sh|bash|zsh|python3?|node)\b"
        ),
    ),
    (
        # Not this container's to do, and outside the folder either way.
        "reaches past the project directory",
        re.compile(
            _START
            + r"(?:sudo|su|mkfs(?:\.\w+)?|shutdown|reboot|halt|poweroff)\b"
            + r"|"
            + _START
            + r"dd\b[^|;&]*\bof=/dev/"
            + r"|"
            + _START
            + r"chmod\s+(?:-[a-zA-Z]*R[a-zA-Z]*|--recursive)\s+\S+\s+/"
            + _END
            + r"|>\s*/dev/(?:sd|nvme|hd|disk)"
        ),
    ),
    (
        # The one pattern nothing else in this list resembles.
        "forks without bound",
        re.compile(r":\s*\(\s*\)\s*\{[^}]*:\s*\|\s*:"),
    ),
)


def command_still_asks(command: str) -> str | None:
    """Why this command still stops at a person in an unattended turn, or ``None``.

    The first matching shape's reason. Shapes are tried in the order above so a
    command matching two is reported by the one whose cost is largest, which is
    also the one a reader most needs to hear.
    """

    for reason, pattern in STILL_ASKS:
        if pattern.search(command):
            return reason
    return None


def arguments_still_ask(arguments: Mapping[str, JsonValue]) -> str | None:
    """The same question asked of a tool call's arguments.

    Reads `COMMAND_ARGUMENT` and nothing else. A call carrying no command has
    no shape to match and returns ``None``, which is the right answer for a
    file deletion and the wrong one for a future command-shaped tool that
    spells its argument differently -- so that tool should spell it this way.
    """

    command = arguments.get(COMMAND_ARGUMENT)
    if not isinstance(command, str):
        return None
    return command_still_asks(command)


__all__ = [
    "COMMAND_ARGUMENT",
    "STILL_ASKS",
    "arguments_still_ask",
    "command_still_asks",
]
