"""The stored-bytes boundary.

Large tool output, uploaded documents and generated reports live here, and
messages, events and graph state hold only the reference. That is what keeps a
context window, an event row and a checkpoint bounded no matter how large a
result is.

Two ways in and two ways out, for two sizes of thing. ``put`` takes bytes a
caller already holds -- a tool result, a generated summary. ``put_stream``
takes an iterator and a ceiling, because an uploaded document is exactly the
case where holding it all first is the bug: a request body that must fit in
memory before it can be stored has a size limit nobody wrote down.
``get`` and ``iter_chunks`` mirror that on the way back -- a caller that
already knows the object is small takes the bytes, and anything serving one to
a client takes the iterator.

Object keys are generated by the store. A caller supplies a tenant, a kind and
content, never a path: accepting a caller-chosen location is how path traversal
and cross-tenant writes get in.

Writes record an owner and reads take a principal, because an id is not a
secret. Artifact ids appear in tool results, event payloads and URLs, and a
store that answered any id belonging to the right tenant would make every one
of those places a capability. "Hard to guess" is not an authorization rule.

Ownership deliberately lives here rather than on ``ArtifactRef``. A reference
travels inside messages and events; who may read the bytes is a fact about the
stored object, not about the pointer, and a pointer that carried it would be
handing out the answer along with the question.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Final, Protocol, runtime_checkable

from agent_workbench.domain.artifacts import ArtifactKind, ArtifactRef

# Large enough that per-chunk overhead is noise, small enough that one chunk
# in flight per request is not a memory budget anybody has to think about.
DEFAULT_CHUNK_BYTES: Final[int] = 262_144


@runtime_checkable
class ArtifactStore(Protocol):
    """Content-addressed storage for bytes that must not travel inline."""

    async def put(
        self,
        *,
        tenant_id: str,
        owner_id: str,
        kind: ArtifactKind,
        media_type: str,
        content: bytes,
        filename: str | None = None,
    ) -> ArtifactRef:
        """Store bytes and return their reference, with size and digest set."""
        ...

    async def put_stream(
        self,
        *,
        tenant_id: str,
        owner_id: str,
        kind: ArtifactKind,
        media_type: str,
        chunks: AsyncIterator[bytes],
        max_bytes: int,
        filename: str | None = None,
    ) -> ArtifactRef:
        """Store a stream, refusing it once it exceeds ``max_bytes``.

        The ceiling is checked as the bytes arrive, not after: a store that
        learns the size only once it has the whole object has already spent
        whatever the sender chose to send. Raises ``OutputTooLargeError``.
        """
        ...

    async def get(
        self, *, tenant_id: str, artifact_id: str, principal_id: str
    ) -> bytes:
        """Read a whole artifact this principal stored.

        For callers that hold the object in memory anyway, or know it is
        small. Anything serving bytes onward wants ``iter_chunks``.

        Raises ``NotFoundError`` for an unknown id, another tenant's, and
        another principal's alike: all three must be indistinguishable to the
        caller, since a distinguishable refusal answers the question it
        declined.
        """
        ...

    def iter_chunks(
        self,
        *,
        tenant_id: str,
        artifact_id: str,
        principal_id: str,
        chunk_bytes: int = DEFAULT_CHUNK_BYTES,
    ) -> AsyncIterator[bytes]:
        """Yield the artifact in pieces, under the same authorization rule.

        Deliberately not ``async def``. Authorization has to happen when this
        is called, not when the first chunk is pulled: a coroutine that only
        refused on first iteration would let a caller commit to a success it
        then could not deliver.

        Raises ``NotFoundError`` on the same three cases as ``get``.
        """
        ...

    async def head(
        self, *, tenant_id: str, artifact_id: str, principal_id: str
    ) -> ArtifactRef:
        """Describe an artifact without transferring it, under the same rule.

        Size, digest and filename are as much the owner's as the bytes.
        """
        ...


__all__ = ["DEFAULT_CHUNK_BYTES", "ArtifactStore"]
