"""The stored-bytes boundary.

Large tool output, uploaded documents and generated reports live here, and
messages, events and graph state hold only the reference. That is what keeps a
context window, an event row and a checkpoint bounded no matter how large a
result is.

Two ways in, for two sizes of thing. ``put`` takes bytes a caller already holds
-- a tool result, a generated summary. ``put_stream`` takes an iterator and a
ceiling, because an uploaded document is exactly the case where holding it all
first is the bug: a request body that must fit in memory before it can be
stored has a size limit nobody wrote down.

Object keys are generated by the store. A caller supplies a tenant, a kind and
content, never a path: accepting a caller-chosen location is how path traversal
and cross-tenant writes get in.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol, runtime_checkable

from agent_workbench.domain.artifacts import ArtifactKind, ArtifactRef


@runtime_checkable
class ArtifactStore(Protocol):
    """Content-addressed storage for bytes that must not travel inline."""

    async def put(
        self,
        *,
        tenant_id: str,
        kind: ArtifactKind,
        media_type: str,
        content: bytes,
        filename: str | None = None,
    ) -> ArtifactRef:
        """Store bytes and return their reference, with size and digest set."""
        ...

    async def put_stream(
        self,
        *,
        tenant_id: str,
        kind: ArtifactKind,
        media_type: str,
        chunks: AsyncIterator[bytes],
        max_bytes: int,
        filename: str | None = None,
    ) -> ArtifactRef:
        """Store a stream, refusing it once it exceeds ``max_bytes``.

        The ceiling is checked as the bytes arrive, not after: a store that
        learns the size only once it has the whole object has already spent
        whatever the sender chose to send. Raises ``OutputTooLargeError``.
        """
        ...

    async def get(self, *, tenant_id: str, artifact_id: str) -> bytes:
        """Read an artifact.

        Raises ``NotFoundError`` both for an unknown id and for an id owned by
        another tenant: the two must be indistinguishable to the caller.
        """
        ...

    async def head(self, *, tenant_id: str, artifact_id: str) -> ArtifactRef:
        """Describe an artifact without transferring it."""
        ...


__all__ = ["ArtifactStore"]
